import './globals.css'

import { Inter } from 'next/font/google'

import { Breadcrumbs } from '@/components/Breadcrumbs'
import { SiteHeader } from '@/components/SiteHeader'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<SiteHeader />
				<main className="flex min-h-screen flex-col">
					<Breadcrumbs className="px-24 pt-8" items={[
						{ children: 'States', href: "#" },
						{ children: 'Texas', href: "#", isLast: true }
					]} />
					{children}
				</main>
			</body>
		</html>
	)
}
